easy_admin:
  entities:
    User:
      # ...
      fields:
        # ...
        - {
            property: "role",
            type: "association",
            label: "Role",
            multiple: false,
          }
